_target_: src.encoders.E4E_Encoder
device: cuda:0
class_name: CelebA
opts:
  batch_size: 1
  test_batch_size: 1
  workers: 2
  test_workers: 2
  image_size: 128
  lpips_type: alex
  lpips_lambda: 0.8
  id_lambda: 0.5
  moco_lambda: 0.0
  l2_lambda: 1.0
  learning_rate: 0.0005
  w_discriminator_lambda: 0.1
  w_discriminator_lr: 2e-5
  w_pool_size: 50
  d_reg_every: 16
  r1: 10
  use_w_pool: true
  dataset_type: ffhq_encode
  max_steps: 100
  start_from_latent_avg: true
